### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ggflempire** [hudsonbrendon/ha_epic_games#6]
When I add an Epic location to HA I get "TypeError: 'NoneType' object is not subscriptable". I have tried multiple locations (US, UK, DE) but always the same error message in the logs... Any idea what to try?

**Comment by Halves0840** [comment]
I managed to work around this by hardcoding the URL in the sensor.py file

```python   
 @property
    def url(self):
        # return f"{BASE_URL}/freeGamesPromotions?locale={self.locale}&country={self.country}&allowCountries={self.allow_countries}"
        return "https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=en-GB&country=GB&allowCountries=GB"
```

No clue what exactly is causing the original URL to fail
